
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")
print ("Hello word")
print ("Update.")